### ISSUE TITLE
Make greentea tools standalone

### ISSUE THREAD

**Issue by rwalton-arm** [ARMmbed/greentea#303]
We'd like to make the greentea tools standalone again, rather than part of the mbed-os-tools mono repo. 

- [X] Bring mbed_host_tests (htrun) into standlone greentea python library #302 @rajkan01 
- [x] Separate Greentea host tools (python) into their own repo @wernerlewis #301 
- [x] Update [the Readme of standalone greentea htrun](https://github.com/ARMmbed/greentea/blob/master/src/htrun/README.md) @rajkan01 #307 307 
- [x] #310
- [x] #309
- [x] #312
- [X] Remove the unused/dead from standalone greentea htrun @LDong-Arm  (won't do, see explanation below)
- [X] Remove [tools/host_tests from mbed-os](https://github.com/ARMmbed/mbed-os/tree/mbed-os-6.11.0/tools/host_tests) @LDong-Arm (won't do, see below)
- [x] Remove unimplemented gt command line arguments @wernerlewis (PR #301 in review )
- [x] Check use and un-used the htrun command line arguments @rajkan01 
- [x] Remove un-implemented htrun command line arguments python source from standalone greentea htrun repo @rajkan01
- [x] Verify fastmodel support works in standalone greentea htrun @rajkan01 ( Unable to verify, see explanation below))
- [x] #314
- [x] #315 @rajkan01 https://github.com/ARMmbed/mbed-os/pull/14932 
- [x] #317
- [x] #318
- [x] #319 @rajkan01 #321 
- [x] #323
- [x] #311
- [x] #313
- [x] Refactor Mbed host-tests to use standalone greentea python lib @rajkan01 https://github.com/ARMmbed/mbed-os/pull/14755 (It is blocked until mbed-greentea PyPI gets released)
- [x] #316

**Comment by LDong-Arm** [comment]
Explanation for scripts in [host_tests](https://github.com/ARMmbed/greentea/tree/65c97b6c8392a0072dcd5f7914d798d7357ee7f2/src/htrun/host_tests):
Some of the scripts are not directly referenced by the code base (e.g. `default_auto.py`), but actually greentea-client can instruct htrun to run the script with specified name:
```c
GREENTEA_SETUP(20, "default_auto");
```
The `host_tests` from htrun itself is in the "search path", but users can also add additional directories using the `-e/--enum-host-tests` option. Also, mbed-os [bundles its own host tests](https://github.com/ARMmbed/mbed-os/tree/mbed-os-6.11.0/tools/host_tests).

**Comment by rajkan01** [comment]
Verify fastmodel support works in standalone greentea htrun: 

`mbed-fastmodel-agent` is an interface python module to ARM fast model and this fastmodel agent is invoked by `htrun` to run host tests with fast models. Unfortunately `mbed-fastmodel-agent` is using pyCADI (based Python 2.7) which is part of the ARM fast model and it got deprecated in the latest version and replaced by Irish CADI which leads to significant changes in the `mbed-fastmodel-agent` to work so I could not able to completely verify the flow of fast model inside htrun and only checked ran the following command to make sure it invokes the fast model agent APIs

**Comment by Patater** [comment]
All tasks closed. Mission complete.
